### ISSUE TITLE
pyproject.toml additions

### ISSUE THREAD

**Issue by unwarymold9171** [unwarymold9171/Py_Cert_Store#11]
Some additional features can be added to the toml file that will help with the PyPi page:

example:
```toml
[project]
description = "A small example package"
readme = "README.md"
...
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"
```
